name: Frontend ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "static/**"
  pull_request:
    branches:
      - main

jobs:
  ci:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CMS_API_KEY: ${{ secrets.CMS_API_KEY }}
      CMS_ENDPOINT: ${{ secrets.CMS_ENDPOINT }}
      # use only development mode
      CMS_DRAFT_KEY: ""
      TZ: "Asia/Tokyo"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: package.json
      - run: corepack enable pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Svelte Check
        run: pnpm check
      - name: Unit test
        run: pnpm test:unit
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
      - name: E2E Test
        run: pnpm test
